# Generated by Django 5.0.6 on 2024-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='products', verbose_name='Product image'),
        ),
    ]
